apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: us.gcr.io/ticketing-dev-314709/payments
        env:
          - name: MONGO_URI
            value: 'mongodb://payments-mongo-srv:27017/tickets'
          - name: NATS_URL
            value: 'https://nats-srv:4222'
          - name: NATS_CLIENT_ID
            valueFrom: 
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: JWT_KEY
            valueFrom:
              secretKeyRef: 
                name: jwt-secret
                key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec: 
  selector:
    app: payments
  ports: 
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000